PreMiD/Localization

- src/Website/contributors.json
- src/Website/store.json
- src/Website/users.json
> New translations!

- src/Website/presence.json
> Okay, this is a weird mistake.

- crowdin.yml
- src/Presence/1337x.json
- src/Presence/9gag.json
- src/Presence/aliexpress.json
- src/Presence/amazon.json
- src/Presence/facebook.json
- src/Presence/general.json
- src/Presence/hypixel.json
- src/Presence/pinterest.json
- src/Presence/premid.json
- src/Presence/spotify.json
- src/Presence/twitter.json
- src/Presence/youtube.json
Reverts PreMiD/Localization#75
> Revert "Revert "Presence Strings""

- src/Website/jobs.json
Strings related to [this](https://github.com/PreMiD/Website/pull/231)  PR.
> Added strings for server join modal

- src/Website/errors.json
- src/Website/footer.json
- src/Website/jobs.json
> :worried: Delete strings, will add them back

- src/Website/presence.json
- src/Website/report.json
https://github.com/PreMiD/Website/pull/310
> :recycle: Updated

- src/Extension/popup.json
> Add messages for safari port

- src/Presence/general.json
To be used in Music Presence Buttons
View Artist and View Playlist
> Added 2 New Strings in the general.json file

- src/Presence/general.json
> Added 1 more

- src/Presence/kahoot.json
Changed Slide to Slide with Content
> Update kahoot.json as requested 

- src/Website/google classroom.json
- src/Website/google docs.json
Adds support for: 
- Google Classroom
- Google Docs
> 🎨  Localisation Support

- src/Presence/rythm.json
https://github.com/PreMiD/Presences/pull/3912
> Translation strings for the Rythm presence

- src/Presence/gmail.json
> feat(gmail): add localization support

- src/Website/presence.json
https://github.com/PreMiD/Website/pull/873
> feat(Website): add URL RegExp information

- src/Presence/kahoot.json
https://github.com/PreMiD/Presences/pull/5975
> feat(kahoot): Add and modify messages

- src/Presence/general.json
Add the string "Currently listening to".
> Add currentlyListening string

- src/Presence/general.json
Add variable for the general.currentlyListening string.
> Add variable to currentlyListening string

- src/Presence/youtube.json
Added:
```json
"youtube.browsingTypeVideos": {
"description": "",
"message": "Browsing through {0} videos"
},
"youtube.studio.viewContent": {
"description": "",
"message": "Viewing their content"
},
"youtube.browsingShorts": {
"description": "",
"message": "Browsing shorts"
},
```
> feat(Youtube): change & add strings

- src/Website/contributors.json
Presence Developer
Presence Developers
> feat: added strings for website

- src/Presence/tiktok.json
Goes with [https://github.com/PreMiD/Presences/pull/7831](https://github.com/PreMiD/Presences/pull/7831)
> feat(tiktok): add strings
